spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forum_db?reconnect=true
    username: afrodite
    password: 1203
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    url: jdbc:mysql://localhost:3306/forum_db
    user: afrodite
    password: 1203
    baseline-on-migrate: true

server:
  port: 8080

api.security.token.secret: "12345678"
